spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.92.128:3306/mall_ums
    username: root
    password: liukaiying1314
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.92.128:8848
  application:
    name: mall-member

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 9901